export const SET_BUY_STATUS = 'CHANGE_BUY_STATUS';
export const SET_BUY_STATUS_FOR_COMPANY = 'SET_BUY_STATUS_FOR_COMPANY';
export const SET_SUM_AMOUNT = 'CHANGE_SUM_AMOUNT';
export const LOAD_ALL_COMPANIES = 'LOAD_ALL_COMPANIES';
export const LOAD_ALL_CURRENCIES = 'LOAD_ALL_CURRENCIES';
export const LOAD_COMPANY_BY_NAME = 'LOAD_COMPANY_BY_NAME';
export const FIND_COMPANY_BY_NAME = 'FIND_COMPANY_BY_NAME';
export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';
export const SET_ACTIVE_COMPANY_CURRENCY = 'SET_ACTIVE_COMPANY_CURRENCY';

export const SET_SORTING_TYPE = 'SET_SORTING_TYPE';
export const FILTER_COMPANIES_BY_NAME = 'FILTER_COMPANIES_BY_NAME';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const LOAD_CENTRAL_BANK_DATA = 'LOAD_CENTRAL_BANK_DATA';
export const LOAD_CENTRAL_BANK_EUR_USD = 'LOAD_CENTRAL_BANK_EUR_USD';

export const sortingType = {
  HIGH_PRICE: "HIGH_PRICE",
  LOW_PRICE: "LOW_PRICE",
  NAME: "NAME",
  GEOLOCATION: "GEOLOCATION"
};
