export const CHANGE_COMPANY_MAIN_INFO_VALUE = "CHANGE_COMPANY_MAIN_INFO_VALUE";
export const SET_INITIAL_COMPANY_MAIN_INFO_STATE = "SET_INITIAL_COMPANY_MAIN_INFO_STATE";
export const CHANGE_WORKING_TIME_VALUE = "CHANGE_WORKING_TIME_VALUE";
