export const SELECT_UNSELECT_CURRENCY = "SELECT_UNSELECT_CURRENCY";
export const CHANGE_CURRENCY_VALUE = "CHANGE_CURRENCY_VALUE";
export const SET_INITIAL_CURRENCY_STATE = "SET_INITIAL_CURRENCY_STATE";