export const SET_BUY_STATUS = 'CHANGE_BUY_STATUS';
export const SET_BUY_STATUS_FOR_COMPANY = 'SET_BUY_STATUS_FOR_COMPANY';
export const SET_SUM_AMOUNT = 'CHANGE_SUM_AMOUNT';
export const LOAD_ALL_COMPANIES = 'LOAD_ALL_COMPANIES';
export const LOAD_COMPANY_BY_NAME = 'LOAD_COMPANY_BY_NAME';
export const FIND_COMPANY_BY_NAME = 'FIND_COMPANY_BY_NAME';